### ISSUE TITLE
Authentication fails for https://github.com/axle-h/vsmt.git/

### ISSUE THREAD

**Issue by antiwarhol** [axle-h/vsmp#1]
Hi, first of all thanks a lot for this cool project.
I have been trying to follow your install instructions on https://ax-h.com/development/raspberry-pi/2020/11/29/very-slow-movie-player.html

I have everything plugged together so far. However, when I run git clone https://github.com/axle-h/vsmp.git , I get an error message
_"Support for password authentication was removed on August 13, 2021. Please use a personal access token instead."_

I'm a newbie and I would be very grateful for tips. 
Thanks for creating this!
Tim

**Comment by axle-h** [comment]
Hi Tim, just spotted this sorry! Hope you managed to fix it? Looks to be an issue with your git client. Maybe you authenticated with github in the past using username & password. You don't need to use authentication to pull a repo anyway so you should be ok to disable it. Alternatively you can sign in again with tokens https://stackoverflow.com/questions/68775869/message-support-for-password-authentication-was-removed-please-use-a-personal
